language: node_js
node_js:
  - 4.2.1

env:
  global:
  - secure: U/LRZONVB9q9vJRU3bmuK93yAr837SmtSBt/FFRDvvmgax/eOqNWcQvZTerc1Pp33Y/bypC8436Z+20UvxepqLPW2Lj4VcQF3vV20WPIqB2Ns7U54iNrCasgsw3aVmQ1utt8xQ8ogybVy6c64Hgl4su3Ad25jlEkGzTXLnjn+JtA3ph/Nt3MuSCxxXuZATeU8K0zKL/gys48BaEomCdyBBBljAX0RVVuhHn7GmxVbYYPtMVndQYSqoSp77eMgaHNZBkYm8zJbGwjN0r4Hdv8rsGVxk6NRDUy86yzXVskdGGdCXXqd5aZ3ealJa5/O/Y2Vk5OobrCaaSVt1B8zwJ2NHlTHBuz+GdlPG9o4XXzEgVVHJDORcjV5OYi7KFNqBxL+UU/UljwD8U3ghcKgbl01CZ6vFlEXxgEmQoHHujxrThZNmfCu8Mw9XI7uXkS0h0hxj9ZYXB3bYeDMO9qE79V/xPkKriaiHDq7y59LJl4/65f9uRQLORH3qlrMsmu5hjfuknjNWPRnY5IqroH5lpW77a3nzp/Sv+JsjXN8tfihzkuIqb1Q5A98ZXwSSeyUZZR4E+CdAMwZJtxrZ0uxLn36VY/d2gTy/nVYH7UJOUpfV9Al6Fb/3komKP9mLv6tjGn+RNJvpX5vGQB9UPrZOxPNmg35nvueqOKr2r2VFe6bec=
  - secure: J3VBR2qKD84AxF/OIe+PHbFdP9qdK0ZQ1zHJi5CSIJp0gknjFhBAtq6PCep0x5jBMYyfQFmkMpTpiLWSzFaGbzabjuygA1lOX6I4EetI6/KDiu5Qj+HdC3vXcz6QcQqljGPDlQEeXDWe3yRBpug8HIWxEWEoCGuQtgjamkSSGsycfpaqNIzTlT/Qti2at9malZ5XRtN/8uic8ic08AiEq+FeZoPG8GGRHLiezS8QtRYIGx4qHkwDKlrQNwm4Uk/ybUI4I66Kx7x0FEPzuzBnC3g7fQs7gGib/4Rx2DVNCsJIkGycWThaNliFZLvF42WAx/3g075fSZsAwXtlMIoeI2w2L23Zvh1KIEW5Au2NNgiHmYaO5dIT/fXONRDzlFkRtp7uf4KGacmWELhPTlf67xhHy6Q/hYM1I2/IODRW79VhtZBBBLbrL6EqnV5CtDVxtphc9RuRU2+QA7CQhPeoiZBcLRwNcL8gwMKn2rLdX1YlEoxSFSWpMezTSgZt3fnzLJy8r+gFwW6axStWK7Tl4hdwiNY2JRfi0u2w6WuNnkICVOTEQe0PWHk61cD/HVrt5OYZPvrzpOf6FJ/7U8wt5iRhY7jWE8G6PuwEG8VzUNuZYaeXMiZEVAeLENgA0hpT0NvCsxUdhbpgnUbpcmRl68LcdEjavV63JbwuFuUpkZw=
  - secure: Zwv8MiHoiL75XiCLhWNCtquyc2WmTw3kb0w4JdXa1fDZfJoTmOHWlBrpnMTX/+tVlxd2IOBI+6Yc8yDTzkvYp9Gxnwx9GxRiQBR5FJbPbVMf9yzar5dn5WVaeOX0sTKkam9FpZpnya5FxrK37Bl1021EClConRbv/6r4BjbH8mVz3f9mxcx/pmBdeiIRqvfTtJICFyKIQX9z3jl3MNahIKvUffzjsdRh8pvB7XbrbnNFiQcB6BGLtyNBwqcWHlzny8bHNXVOnou5p3SvmnLVqta8jQX1ahp5WUsaPaiZxt+i7/kGMDvF2dVB3w3XaA9xago/WDAB7i1qkyTxJ5a45pURpEZ0R22clK5tM0XxM8ymNMqVFkOlZM+lJJKWEHtmFt5W+cineuDbqby1K1J60gaoqRa0ZoBWcg85ZB1gZ0dSrUWFy69vYXD6Q/H1DHsAQVQZQkCGJL46dXOCM592FGIhA4Yfr4+wh+xddxcKPRK5WG6HK7uh3ktCpOx6uonpoWsShwZOqkyOg+3SxiQSEgGwSJdQNcsk25aJF0BL+C4Q3FCuhqEtkUdpMdXcF7gEJ59oJvgAAdkRqmfLt2T7mCKVyFT+he+LMWcznCYJcw1EICMRQFtrfyoiA2fqu5d8HdjMCdgm/FMxpQm/lReFQzfIL0nwWxx+mhW3ocdvvos=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
